version: '3'

services:
  # TODO
  # monitoring-service

  mysql:
    image: mysql:latest
    networks:
      default:
        aliases:
            - mysql
    ports:
      - 3306:3306
    volumes:
      - ./../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: applifting
      MYSQL_PASSWORD: root
